# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'TestRealTimeCutVADLibraryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealTimeCutVADLibrary', :git => 'https://github.com/helloooideeeeea/RealTimeCutVADLibrary.git', :tag => '1.0.2'
  # Pods for TestRealTimeCutVADLibraryApp

end

